spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB.username}
    password: ${DB.password}
    url: ${DB.url}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE.clientId}
            client-secret: ${GOOGLE.secretKey}
            scope: # google API의 범위 값
              - profile
              - email
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10

  config:
    import:
      - "classpath:application-secret.yml"
jwt:
  secret: ${JWT.secretKey}

football:
  apiToken: ${FOOTBALL-API.token}